---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  replacement: true
  name: cinder-rabbitmq
  labels:
    name: cinder-rabbitmq-type
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: cinder-rabbitmq-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    pod:
      replicas:
        server: 1
...
