---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-barbican
  replacement: true
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: ucp-barbican-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    pod:
      replicas:
        api: 1
...
